spring.data.mongodb.uri=mongodb+srv://np5825277_db_user:Naresh_8817@m0.gknmqdr.mongodb.net/annotationDB?appName=M0
server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework=DEBUG
logging.level.org.mongodb.driver=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always