spring.data.mongodb.uri=mongodb+srv://np5825277_db_user:Ni7HC6EIuMapEbIh@m0.gknmqdr.mongodb.net/annotationDB?appName=M0
server.port=8080
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB